seed: 42
device: "cpu"        # or "cpu"

dataset:
  root: "./data"
  split: "train"        # train | test
  batch_size: 64
  normalize_range: [0, 1]  # [0, 1] or [-1, 1]

noise:
  sigmas: [0.0, 0.1, 0.2, 0.3, 0.5, 0.7, 1.0]
  schedule: "linear"    # linear | cosine | custom
  num_levels: 7
  min_sigma: 0.0
  max_sigma: 1.0

visualization:
  grid_nrow: 8
  animation_fps: 2
  plot_dpi: 100
  figsize: [12, 8]

output_dir: "./outputs"

# Experiment settings
experiment:
  num_batches: 2      # for add-noise command
  num_images: 16      # for animate command
  save_individual: false  # save individual noised images